#!/bin/bash
# @file system_info
# @brief A simple bash script to print out system information.
# @author Snehal Sanghvi
# @date September 4 2017
# @version 1.0


FILE="system_data.txt"

echo "Dumped all the system data to a file called system_data.txt"
echo "System information:" >> $FILE
echo "----------------------------------------" >> $FILE
echo "Operating system type:"  $(uname -o) >> $FILE
echo "OS Distribution:"  $(cat /etc/*release| grep 'DISTRIB_ID' |cut -c12-) $(cat /etc/*release | grep 'DISTRIB_RELEASE' | cut -c17-) >> $FILE
echo "Kernel version:" $(uname -r) >> $FILE
echo "Information on kernel build:" $(uname -s) $(uname -r) $(uname -v) >> $FILE
echo "Kernel gcc version build:" $(cat /proc/version | grep -o -P '.gcc.{0,15}' | cut -c14-) >> $FILE
echo "Kernel build time:" $(uname -v|cut -c8-) >> $FILE
echo "System Architecture:" $(uname -m) >> $FILE
echo "----------------------------------------" >> $FILE

#end of file
